import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Inter } from 'next/font/google'
import { LayoutProviders } from './layout.providers'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
    >
      <LayoutProviders>
        <body className="min-h-screen bg-gray-50">
          <main className="container-custom py-8">{children}</main>
          <footer className="text-center text-xs text-gray-400 opacity-50 mt-8 mb-4">
            Only for educational purposes
          </footer>
        </body>
      </LayoutProviders>
    </html>
  )
}
